### ISSUE TITLE
genreg似乎无效

### ISSUE THREAD

**Issue by cd711** [davyxu/protoplus#3]
genreg似乎无效
我也拉取代码运行了一下 genreg参数始终拿不到true，有点像go的bug，
go 1.16.3
go get -u -v github.com/davyxu/protoplus

目前在本地编译了一份protoplus写死了genreg参数在使用

**Comment by davyxu** [comment]
检查你自己的命令行参数, --genreg=true

**Comment by cd711** [comment]
我今天重新go get -u -v github.com/davyxu/protoplus以后运行正常了
另外
--genreg=true 
-genreg
-genreg=true
都是ok的
